update to flavio v2.6.1 (#64)
* use UT angle gamma instead of CKM phase delta

* update par_ckm

* update github actions workflow

* fix tests

* temp fix for ImportError: cannot import name 'packaging' from 'pkg_resources'

* update version

* fix test_ckm

* fix install requirements